Public Class REPLYCODES

#Region "REPLYCODES"
    Public RPL_UPDATE_NONEX As String = "602"
    Public RPL_UPDATE_EXIST As String = "603"
    Public RPL_WOLSERV As String = "605"
    Public RPL_UPDATE_FTP As String = "606"
    Public RPL_QUIT As String = "607"
    Public RPL_GAMERES_SERV As String = "608"
    Public RPL_LADDERSERV As String = "609"
    Public RPL_LOBBYCOUNT As String = "610"
    Public RPL_WDTSERVER As String = "611"
    Public RPL_MANGLERSERV As String = "612"
    Public RPL_TICKETSERV As String = "613"
    Public RPL_PINGERVER As String = "615"

    Public RPL_LOCALE As String = "309"
    Public RPL_LOCALESET As String = "310"
    Public RPL_LISTSTART As String = "321"
    Public RPL_LISTGAME As String = "326"
    Public RPL_LIST As String = "327"
    Public RPL_CODEPAGE As String = "328"
    Public RPL_CODEPAGESET As String = "329"
    Public RPL_ENDOFLIST As String = "323"
    Public RPL_TOPIC As String = "332"
    Public RPL_GETBUDDY As String = "333"
    Public RPL_ADDBUDDY As String = "334"
    Public RPL_DELBUDDY As String = "335"
    Public RPL_NAMREPLY As String = "353"
    Public RPL_SQUADINFO As String = "358"
    Public RPL_ENDOFNAMES As String = "366"
    '374 -

    Public RPL_MOTDSTART As String = "375"
    Public RPL_MOTD As String = "372"
    Public RPL_ENDOFMOTD As String = "376"
    Public ERR_APGARMISSMATCH As String = "378"
    Public RPL_VERCHK_NOTNEEDED As String = "379"
    Public RPL_PAGE As String = "389"
    Public RPL_TIME As String = "391"
    Public RPL_FINDUSEREX As String = "398"
    Public RPL_INSIDER As String = "399"

    Public ERR_NOSUCHNICK As String = "401"
    Public ERR_NOSUCHCHANNEL As String = "403"
    Public ERR_UNKNOWNCOMMAND As String = "421"
    Public ERR_NOMOTD As String = "422"
    Public ERR_NOTFOUNDONLADDER As String = "425"
    Public ERR_NONICKNAMEGIVEN As String = "431"
    Public ERR_ERRORNEUSNICKNAME As String = "432"
    Public ERR_NICKNAMEINUSE As String = "433"
    Public ERR_UNAVAILRESOURCE As String = "437"
    Public ERR_SQUADIDNOEXIST As String = "439"
    Public ERR_USERNOTINCHANNEL As String = "441"
    Public ERR_NOTONCHANNEL As String = "442"
    Public ERR_USERONCHANNEL As String = "443"
    Public ERR_NEEDMOREPARAMS As String = "461"
    Public ERR_ALREADYREGISTERED As String = "462"

    Public ERR_CHANNELISFULL As String = "471"
    Public ERR_BANNEDFROMCHAN As String = "474"
    Public ERR_BADCHANNELKEY As String = "475"
    Public ERR_BADCHANMASK As String = "476"
    Public ERR_CHANOPRIVSNEEDED As String = "482"

#End Region
End Class
